# Generated by Django 4.2.28 on 2026-02-25 08:38

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Korisničko ime')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('RADNIK', 'Radnik')], default='RADNIK', max_length=10, verbose_name='Uloga')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Korisnik',
                'verbose_name_plural': 'Korisnici',
            },
        ),
        migrations.CreateModel(
            name='Artikal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_broj', models.CharField(default=core.models.generate_random_broj, editable=False, max_length=20, unique=True, verbose_name='Broj artikla')),
                ('sifra_artikla', models.CharField(max_length=100, verbose_name='Šifra artikla')),
                ('naziv_artikla', models.CharField(max_length=255, verbose_name='Naziv artikla')),
                ('kolicina', models.PositiveIntegerField(default=0, verbose_name='Količina')),
                ('cijena', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cijena (KM)')),
                ('datum_unosa', models.DateTimeField(auto_now_add=True, verbose_name='Datum unosa')),
                ('unio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uneseni_artikli', to=settings.AUTH_USER_MODEL, verbose_name='Unio')),
            ],
            options={
                'verbose_name': 'Artikal',
                'verbose_name_plural': 'Artikli',
                'ordering': ['-datum_unosa'],
            },
        ),
        migrations.CreateModel(
            name='Zaduzenje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.PositiveIntegerField(verbose_name='Količina')),
                ('datum_dodjele', models.DateTimeField(auto_now_add=True, verbose_name='Datum dodjele')),
                ('status', models.CharField(choices=[('DODIJELJENO', 'Dodijeljeno'), ('ZAVRSENO', 'Završeno')], default='DODIJELJENO', max_length=15, verbose_name='Status')),
                ('datum_zavrsetka', models.DateTimeField(blank=True, null=True, verbose_name='Datum završetka')),
                ('artikal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaduzenja', to='core.artikal', verbose_name='Artikal')),
                ('kome_izdato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zaduzenja', to=settings.AUTH_USER_MODEL, verbose_name='Kome izdato')),
                ('zavrsio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zavrsena_zaduzenja', to=settings.AUTH_USER_MODEL, verbose_name='Završio')),
            ],
            options={
                'verbose_name': 'Zaduženje',
                'verbose_name_plural': 'Zaduženja',
                'ordering': ['-datum_dodjele'],
            },
        ),
    ]
