# Generated by Django 4.2.28 on 2026-02-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_firme', models.CharField(max_length=255, verbose_name='Naziv firme')),
                ('kontakt_osoba', models.CharField(blank=True, max_length=150, verbose_name='Kontakt osoba')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresa', models.TextField(blank=True, verbose_name='Adresa')),
                ('grad', models.CharField(blank=True, max_length=100, verbose_name='Grad')),
                ('drzava', models.CharField(blank=True, default='Bosna i Hercegovina', max_length=100, verbose_name='Država')),
                ('opis', models.TextField(blank=True, verbose_name='Opis (šta nabavljamo)')),
                ('napomena', models.TextField(blank=True, verbose_name='Interna napomena')),
                ('aktivan', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum kreiranja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum izmjene')),
            ],
            options={
                'verbose_name': 'Dobavljač',
                'verbose_name_plural': 'Dobavljači',
                'ordering': ['naziv_firme'],
            },
        ),
        migrations.AddField(
            model_name='artikal',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artikli', to='core.supplier', verbose_name='Dobavljač'),
        ),
    ]
